version: '3.7'
services:
  shoppingservice:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./Dockerfile
    expose:
      - "4567"
    ports:
      - 4567:4567
    networks:
      - shopping
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    networks:
      - shopping
    environment:
      MONGO_INITDB_DATABASE: CartDB
    ports:
      - "27017:27017"
networks:
  shopping:
    driver: bridge